server:
  port: 8082
management:
  port: 9092
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
     defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msadb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

